Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: multi-node
      NodeType: dc2.large
      NumberOfNodes: 2
      DBName: your_database_name
      MasterUsername: your_master_username
      MasterUserPassword: your_master_password
      ClusterSubnetGroupName: your_subnet_group_name
      VpcSecurityGroupIds:
        - your_security_group_id
